# Generated by Django 3.0.7 on 2020-07-01 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('directors', models.CharField(blank=True, max_length=100)),
                ('urlFilm', models.CharField(blank=True, max_length=1000)),
                ('date_published', models.DateTimeField(blank=True, verbose_name='date published')),
                ('contentFilm', models.CharField(blank=True, max_length=500)),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date update')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='profile_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
