# Generated by Django 3.0.7 on 2020-07-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmpost',
            name='image',
        ),
    ]
