# Generated by Django 3.0.7 on 2020-07-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_auto_20200701_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmpost',
            name='typeFilm',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
