# Generated by Django 3.0.7 on 2020-07-08 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0006_filmpost_typefilm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChairPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_chair', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShowTimePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('amount_chair', models.IntegerField(blank=True, default=0, null=True)),
                ('time_show', models.DateTimeField()),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale_order.ChairPost')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.FilmPost')),
            ],
        ),
    ]
