# Generated by Django 3.0.7 on 2020-07-13 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0006_filmpost_typefilm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_show', models.DateTimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film', to='film.FilmPost')),
            ],
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chairs', to='film_ticket.Room')),
            ],
        ),
    ]
