# Generated by Django 3.0.7 on 2020-07-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_show',
            field=models.DateTimeField(null=True),
        ),
    ]
